// languageMaps.js

const languageMapEng = {
    rus: 'Russian',
    eng: 'English',
    pol: 'Polish',
    ukr: 'Ukrainian',
    hye: 'Armenian',
    kaz: 'Kazakh',
    lit: 'Lithuanian',
    spa: 'Spanish',
    fra: 'French',
    deu: 'German',
    ita: 'Italian',
    por: 'Portuguese',
    nld: 'Dutch',
    dan: 'Danish',
    swe: 'Swedish',
    nor: 'Norwegian',
    fin: 'Finnish',
    est: 'Estonian',
    lav: 'Latvian',
    ces: 'Czech',
    slk: 'Slovak',
    slv: 'Slovenian',
    hrv: 'Croatian',
    srp: 'Serbian',
    bos: 'Bosnian',
    mkd: 'Macedonian',
    bul: 'Bulgarian',
    ell: 'Greek',
    tur: 'Turkish',
    heb: 'Hebrew',
    ara: 'Arabic',
    fas: 'Persian',
    urd: 'Urdu',
    hin: 'Hindi',
    ben: 'Bengali',
    mar: 'Marathi',
    tel: 'Telugu',
    tam: 'Tamil',
    guj: 'Gujarati',
    kan: 'Kannada',
    mal: 'Malayalam',
    ori: 'Oriya',
    pan: 'Punjabi',
    sin: 'Sinhala',
    tha: 'Thai',
    khm: 'Khmer',
    mya: 'Burmese',
    lao: 'Lao',
    vie: 'Vietnamese',
    ind: 'Indonesian',
    msa: 'Malay',
    fil: 'Filipino',
    jpn: 'Japanese',
    kor: 'Korean',
    zho: 'Chinese (Simplified)',
    cht: 'Chinese (Traditional)',
  };
  
const languageMapRus = {
    rus: 'Русский',
    eng: 'Английский',
    pol: 'Польский',
    ukr: 'Украинский',
    hye: 'Армянский',
    kaz: 'Казахский',
    lit: 'Литовский',
    spa: 'Испанский',
    fra: 'Французский',
    deu: 'Немецкий',
    ita: 'Итальянский',
    por: 'Португальский',
    nld: 'Голландский',
    dan: 'Датский',
    swe: 'Шведский',
    nor: 'Норвежский',
    fin: 'Финский',
    est: 'Эстонский',
    lav: 'Латышский',
    ces: 'Чешский',
    slk: 'Словацкий',
    slv: 'Словенский',
    hrv: 'Хорватский',
    srp: 'Сербский',
    bos: 'Боснийский',
    mkd: 'Македонский',
    bul: 'Болгарский',
    ell: 'Греческий',
    tur: 'Турецкий',
    heb: 'Иврит',
    ara: 'Арабский',
    fas: 'Персидский',
    urd: 'Урду',
    hin: 'Хинди',
    ben: 'Бенгальский',
    mar: 'Маратхи',
    tel: 'Телугу',
    tam: 'Тамильский',
    guj: 'Гуджарати',
    kan: 'Каннада',
    mal: 'Малаялам',
    ori: 'Ория',
    pan: 'Панджаби',
    sin: 'Сингальский',
    tha: 'Тайский',
    khm: 'Кхмерский',
    mya: 'Бирманский',
    lao: 'Лаосский',
    vie: 'Вьетнамский',
    ind: 'Индонезийский',
    msa: 'Малайский',
    fil: 'Филиппинский',
    jpn: 'Японский',
    kor: 'Корейский',
    zho: 'Китайский (Упрощенный)',
    cht: 'Китайский (Традиционный)',
  };
  
  export { languageMapRus, languageMapEng};
  